services:
  accounts:
    image: "mohamedtamer0/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mohamedtamer0
networks:
  eazybank:
    driver: "bridge"